### ISSUE TITLE
NPM installation issue ensure-package-manager.js missing

### ISSUE THREAD

**Issue by jamesjjk** [MartinHelmut/number-generator#591]
We are having an issue installing using NPM:
- node v10.16.2
- npm v6.9.0

Debug log:
```
70 verbose stack Error: number-generator@4.0.2 preinstall: `node ./scripts/ensure-package-manager.js`
70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
70 verbose stack     at EventEmitter.emit (events.js:198:13)
70 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
70 verbose stack     at ChildProcess.emit (events.js:198:13)
70 verbose stack     at maybeClose (internal/child_process.js:982:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
71 verbose pkgid number-generator@4.0.2

73 verbose Darwin 18.0.0
74 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "number-generator" "--save"
75 verbose node v10.16.2
76 verbose npm  v6.9.0
77 error code ELIFECYCLE
78 error errno 1
79 error number-generator@4.0.2 preinstall: `node ./scripts/ensure-package-manager.js`
79 error Exit status 1
80 error Failed at the number-generator@4.0.2 preinstall script.
80 error This is probably not a problem with npm. There is likely additional logging output above.
81 verbose exit [ 1, true ]
```

**Comment by MartinHelmut** [comment]
Hey, thank you for reporting this! This should not happen on install and is only thought as a local script. I will change the check to be done in the script `prepare` and publish a new version right away with the fix.

**Comment by jamesjjk** [comment]
You are a star! Excellent package!

**Comment by MartinHelmut** [comment]
Alright, here we go, number-generator@4.0.4 is published with a fix for this. Now yarn, pnpm and npm shall work :)
